# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: mdbook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.10.6


      - name: build mdbook
        shell: bash
        run: |
          cargo binstall -y mdbook-mermaid
          mdbook build books/wjson -d `pwd`/mysite/static/wjson
          mdbook build books/inside-duckdb -d `pwd`/mysite/static/inside-duckdb

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.19.1
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          BUILD_DIR: mysite
          # Provide personal access token
          # TOKEN: ${{ secrets.TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
